# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

services:
  cipherserver:
    image: cipherserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 23456
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:23456
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
